### ISSUE TITLE
Slightly easier way to auth

### ISSUE THREAD

**Issue by james-flume** [jeffkowalski/flume#1]
Hi @jeffkowalski thanks for using the Flume API! 

Just wanted to let you know that we released the official Flume Personal API earlier this month.
[Guide](https://flumetech.readme.io/docs) & [Reference](https://flumetech.readme.io/reference#introduction)

You will be able to authenticate without having to do any redirecting. Thanks!

**Comment by jeffkowalski** [comment]
Excellent news, @james-flume!  I'll make the necessary adjustments.  Thanks for a great product and for your pro-active suggestion.

**Comment by james-flume** [comment]
Of course!
